apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
  labels:
    app: eshop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-db-pod
      app: eshop-app
  template: # from pod definition
    metadata:
      name: mysql-db-pod
      labels:
        name: mysql-db-pod
        app: eshop-app
    spec:
      containers:
        - name: mysql-db
          image: bkntrq/mysql-db:1.0
          ports:
            - containerPort: 3306
          args: ["--default-authentication-plugin=mysql_native_password"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-db-storage
      volumes:
        - name: mysql-db-storage
          persistentVolumeClaim:
            claimName: mysql-db-claim
