apiVersion: v1
kind: Service
metadata:
  name: eshop-front
  labels:
    name: eshop-front-service
    app: eshop-app
spec:
  type: LoadBalancer #change if not on GCP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: eshop-front-pod
    app: eshop-app