apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    name: mysql-db-service
    app: eshop-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-db-pod
    app: eshop-app