apiVersion: v1
kind: Service
metadata:
  name: similarity-calculator
  labels:
    name: similarity-calculator-service
    app: eshop-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: similarity-calculator-pod
    app: eshop-app